[build]
  functions = "netlify/functions"
[build.environment]
  NETLIFY = "true"
[dev]
  functions = "netlify/functions"
[[redirects]]
  from = "/ssr"
  to = "/.netlify/functions/ssr"
  force = true
  status = 200